services:
  docmost:
    container_name: docmost
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: ${DOCMOST_APP_URL}
      APP_SECRET: ${DOCMOST_APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      REDIS_URL: redis://redis:6379
      DISABLE_TELEMETRY: true
      DRAWIO_URL: https://embed.diagrams.net
      STORAGE_DRIVER: local
      FILE_UPLOAD_SIZE_LIMIT: 100mb
      PID: ${PID}
      GID: ${GID}
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - ./docmost:/app/data/storage
  db:
    image: postgres:16-alpine
    container_name: postgres16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - ./redis_data:/data
networks: {}
