services:
    server:
        container_name: authentik
        networks:
            - proxynet
        deploy:
            resources:
                limits:
                    pids: 2048
        privileged: true
        environment:
            - TZ=Europe/Berlin
            - HOST_OS=Unraid
            - HOST_HOSTNAME=Tower
            - HOST_CONTAINERNAME=authentik
            - AUTHENTIK_REDIS__HOST=${AUTHENTIK_REDIS__HOST}
            - AUTHENTIK_POSTGRESQL__HOST=${AUTHENTIK_POSTGRESQL__HOST}
            - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_POSTGRESQL__USER}
            - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_POSTGRESQL__NAME}
            - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_POSTGRESQL__PASSWORD}
            - AUTHENTIK_ERROR_REPORTING__ENABLED=${AUTHENTIK_ERROR_REPORTING__ENABLED}
            - AUTHENTIK_SECRET_KEY=jJpmGtRPqf5D3rbMnVuUW8AHCzEx42Zc
            - AUTHENTIK_REDIS__PASSWORD=redis
            - AUTHENTIK_BOOTSTRAP_PASSWORD=!Nokia3510I!
            - AUTHENTIK_BOOTSTRAP_TOKEN=akadmin
            - AUTHENTIK_BOOTSTRAP_EMAIL=admin@homelab.local
            - AUTHENTIK_REDIS__DB=1
        labels:
            - net.unraid.docker.managed=dockerman
            - net.unraid.docker.webui=http://[IP]:[PORT:9000]
            - net.unraid.docker.icon=https://raw.githubusercontent.com/ibracorp/app-logos/main/authentik/authentik.png
        ports:
            - 9000:9000/tcp
            - 9443:9443/tcp
        volumes:
            - /mnt/user/appdata/authentik/templates/:/templates:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /mnt/user/appdata/authentik/media/:/media:rw
        ulimits:
            nofile:
                soft: 10240
                hard: 10240
        dns:
            - 192.168.178.3
        image: ghcr.io/goauthentik/server:2025.4.2
        command: server
    worker:
        container_name: authentik-worker
        networks:
            - proxynet
        deploy:
            resources:
                limits:
                    pids: 2048
        environment:
            - TZ=Europe/Berlin
            - HOST_OS=Unraid
            - HOST_HOSTNAME=Tower
            - HOST_CONTAINERNAME=authentik-worker
            - AUTHENTIK_REDIS__HOST=${AUTHENTIK_REDIS__HOST}
            - AUTHENTIK_POSTGRESQL__HOST=${AUTHENTIK_POSTGRESQL__HOST}
            - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_POSTGRESQL__USER}
            - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_POSTGRESQL__NAME}
            - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_POSTGRESQL__PASSWORD}
            - AUTHENTIK_ERROR_REPORTING__ENABLED=true
            - AUTHENTIK_SECRET_KEY=jJpmGtRPqf5D3rbMnVuUW8AHCzEx42Zc
            - AUTHENTIK_REDIS__PASSWORD=redis
            - AUTHENTIK_BOOTSTRAP_PASSWORD=!Nokia3510I!
            - AUTHENTIK_BOOTSTRAP_TOKEN=akadmin
            - AUTHENTIK_BOOTSTRAP_EMAIL=admin@homelab.local
            - AUTHENTIK_REDIS__DB=1
        labels:
            - net.unraid.docker.managed=dockerman
            - net.unraid.docker.icon=https://raw.githubusercontent.com/ibracorp/app-logos/main/authentik-worker/authentik_worker.png
        volumes:
            - /mnt/user/appdata/authentik/backups:/backups:rw
            - /mnt/user/appdata/authentik/media:/media:rw
            - /mnt/user/appdata/authentik/certs:/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - /mnt/user/appdata/authentik/templates:/templates:rw
        restart: unless-stopped
        user: root
        dns:
            - 192.168.178.3
        image: ghcr.io/goauthentik/server:2025.4.2
        command: worker
    proxy:
        container_name: authentik-Proxy
        networks:
            - proxynet
        deploy:
            resources:
                limits:
                    pids: 2048
        environment:
            - TZ=Europe/Berlin
            - HOST_OS=Unraid
            - HOST_HOSTNAME=Tower
            - HOST_CONTAINERNAME=authentik-Proxy
            - AUTHENTIK_HOST=https://auth.homelab.muehlendick.xyz/
            - AUTHENTIK_INSECURE=${AUTHENTIK_INSECURE}
            - AUTHENTIK_TOKEN=A8XyKgLeiKjwghso2xyAkaNxgYntEfFEOuRfUR4QOozCjzprgjwTFrYWC5pI
        labels:
            - net.unraid.docker.managed=dockerman
            - net.unraid.docker.icon=https://raw.githubusercontent.com/MacVille/docker-images/refs/heads/main/images/authentik_proxy.png
        ports:
            - 9001:9000/tcp
            - 9444:9443/tcp
        dns:
            - 192.168.178.3
        image: ghcr.io/goauthentik/proxy:2025.4.2
    rac:
        container_name: authentik-RAC
        networks:
            - proxynet
        deploy:
            resources:
                limits:
                    pids: 2048
        environment:
            - TZ=Europe/Berlin
            - HOST_OS=Unraid
            - HOST_HOSTNAME=Tower
            - HOST_CONTAINERNAME=authentik-RAC
            - AUTHENTIK_HOST=https://auth.muehlendick.xyz/
            - AUTHENTIK_INSECURE=${AUTHENTIK_INSECURE}
            - AUTHENTIK_TOKEN=clZxf93InIM3zxCEHwKohyTQzHCOAS79tT43clmyeXmEc6olFXUZ8E8egT3u
        labels:
            - net.unraid.docker.managed=dockerman
        ports:
            - 9002:9000/tcp
            - 9445:9443/tcp
        image: ghcr.io/goauthentik/rac:2025.4.2
    ldap:
        container_name: authentik-LDAP
        networks:
            - proxynet
        deploy:
            resources:
                limits:
                    pids: 2048
        environment:
            - TZ=Europe/Berlin
            - HOST_OS=Unraid
            - HOST_HOSTNAME=Tower
            - HOST_CONTAINERNAME=authentik-LDAP
            - AUTHENTIK_HOST=https://auth.homelab.muehlendick.xyz
            - AUTHENTIK_INSECURE=${AUTHENTIK_INSECURE}
            - AUTHENTIK_TOKEN=tQ8nVXwYiTd0q8geLYkEbqe3Y9FwG2lBjc6giRZil8ph9r7Lt36SkjJOLsBZ
        labels:
            - net.unraid.docker.managed=dockerman
            - net.unraid.docker.icon=https://github.com/MacVille/docker-images/blob/main/images/authentik_ldap.png?raw=true
        ports:
            - 3899:389/tcp
        dns:
            - 192.168.178.3
        image: ghcr.io/goauthentik/ldap:2025.4.2
networks:
    proxynet:
        external: true
        name: proxynet