services:
    server:
        container_name: authentik
        networks:
            - proxynet
        deploy:
            resources:
                limits:
                    pids: 2048
        privileged: true
        environment:
            - TZ=Europe/Berlin
            - HOST_OS=Unraid
            - HOST_HOSTNAME=Tower
            - HOST_CONTAINERNAME=authentik
            - AUTHENTIK_REDIS__HOST'='192.168.178.2
            - AUTHENTIK_POSTGRESQL__HOST'='postgresql13
            - AUTHENTIK_POSTGRESQL__USER'='authentik
            - AUTHENTIK_POSTGRESQL__NAME'='authentik
            - AUTHENTIK_POSTGRESQL__PASSWORD'='authentik
            - AUTHENTIK_ERROR_REPORTING__ENABLED'='true
            - AUTHENTIK_SECRET_KEY'='jJpmGtRPqf5D3rbMnVuUW8AHCzEx42Zc
            - AUTHENTIK_REDIS__PASSWORD'='redis
            - AUTHENTIK_BOOTSTRAP_PASSWORD'='!Nokia3510I!
            - AUTHENTIK_BOOTSTRAP_TOKEN'='akadmin
            - AUTHENTIK_BOOTSTRAP_EMAIL'='admin@homelab.local
            - AUTHENTIK_REDIS__DB'='1
        labels:
            - net.unraid.docker.managed=dockerman
            - net.unraid.docker.webui='http://[IP]:[PORT:9000]'
            - net.unraid.docker.icon='https://raw.githubusercontent.com/ibracorp/app-logos/main/authentik/authentik.png'
        ports:
            - 9000:9000/tcp
            - 9443:9443/tcp
        volumes:
            - /mnt/user/appdata/authentik/templates/':'/templates':'rw
            - /var/run/docker.sock':'/var/run/docker.sock':'ro
            - /mnt/user/appdata/authentik/media/':'/media':'rw
        ulimits:
            nofile:
                soft: 10240
                hard: 10240
        dns:
            - 192.168.178.3
        image: ghcr.io/goauthentik/server:2025.4.2
        command: server
networks:
    proxynet:
        external: true
        name: proxynet