services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - ./data:/data
    ports:
      - 3000:3000
    environment:
      MEILI_ADDR= http://meilisearch:7700
      BROWSER_WEB_URL= http://chrome:9222
      DATA_DIR=${DATA_DIR}
      MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      NEXTAUTH_URL=${NEXTAUTH_URL}
      NEXTAUTH_SECRET=S${NEXTAUTH_SECRET}
      OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      INFERENCE_TEXT_MODEL=${INFERENCE_TEXT_MODEL}
      INFERENCE_IMAGE_MODE=${INFERENCE_IMAGE_MODE}
      DISABLE_SIGNUPS=${DISABLE_SIGNUPS}
      OCR_LANGS=${OCR_LANGS}
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./meilisearch:/meili_data
networks: {}
